FROM nginx
LABEL Description=" This is application frontend image for H-M-System application"
LABEL Maintainer="dattasaibattu@gmail.com"
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
